version: 2.1

orbs:
  python: circleci/python@2.0.3

executors:
  py-3-10:
    docker:
      - image: cimg/python:3.10.6
    resource_class: small

jobs:
  test:
    parallelism: 1
    executor: py-3-10
    steps:
      - checkout
      # use Python orb to handle dependencies installation, incl, caching.
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run unit tests
          command: |
            python -m unittest discover -s tests
          environment:
            PYTHONPATH: src

workflows:
  main:
    jobs:
      - test
