version: 2.1

orbs:
  python: circleci/python@2.0.3

executors:
  py-3-10:
    docker:
      - image: cimg/python:3.10.6
    resource_class: small

jobs:
  test:
    parallelism: 2
    executor: py-3-10
    steps:
      - checkout
      # use Python orb to handle dependencies installation, incl, caching.
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run unit tests
          command: |
            TEST_FILES=$(circleci tests glob "tests/**/test_*.py" | circleci tests split --split-by=timings)

            # debug
            echo "test files to run:\n\n$TEST_FILES\n"

            poetry run pytest $TEST_FILES
          environment:
            PYTHONPATH: src
      - store_test_results:
          path: report.xml

workflows:
  main:
    jobs:
      - test
